export const GET_BLOG_LIST = "GET_BLOG_LIST"
export const GET_BLOG_DETAIL = "GET_BLOG_DETAIL"

export const ADD_TAG = "ADD_TAG"
export const FIND_TAGS_SUCCESS = "FIND_TAGS_SUCCESS"
export const CHOOSE_TAGS_SUCCESS = "CHOOSE_TAGS_SUCCESS"
export const DELETE_TAGS_SUCCESS = "DELETE_TAGS_SUCCESS"

export const POST_NEW_POST_SUCCESS = "POST_NEW_POST_SUCCESS"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"

export const CHANGE_NEW_POST_STATE= "CHANGE_NEW_POST_STATE"

export const CHANGE_NEW_COMMENT_STATE= "CHANGE_NEW_COMMENT_STATE"

export const GET_ERROR = "GET_ERROR"

export const GET_LIKE_POST_SUCCESS = "GET_LIKE_POST_SUCCESS"
export const TOGGLE_LIKE_POST_SUCCESS = "TOGGLE_LIKE_POST_SUCCESS"