export const LOGIN = "LOGIN"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_CHECK = "LOGIN_CHECK"
export const LOGIN_CONFIRM = "LOGIN_CONFIRM"
export const LOGIN_REFRESH = "LOGIN_REFRESH"
export const LOGIN_CHECK_ERROR = "LOGIN_CHECK_ERROR"
export const LOGOUT = "LOGOUT"