export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAILURE = "GET_TODO_FAILURE"

export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS"
export const POST_TODO_FAILURE = "POST_TODO_FAILURE"

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

export const COMPLETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const COMPLETE_TODO_FAILURE = "DELETE_TODO_FAILURE"

export const TODO_CLEAR = "TODO_CLEAR"