export const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS"
export const GET_FOOD_FAILURE = "GET_FOOD_FAILURE"

export const RELOAD_FOOD = "RELOAD_FOOD"
export const SELECT_FOOD = "SELECT_FOOD"
export const DELETE_FOOD = "DELETE_FOOD"